<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <MiniExcelRustPackageVersion Condition="'$(MiniExcelRustPackageVersion)' == ''">0.1.0-benchmark</MiniExcelRustPackageVersion>
    <MiniExcelVersion Condition="'$(MiniExcelVersion)' == ''">1.46.0</MiniExcelVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MiniExcel" Version="[$(MiniExcelVersion)]" />
    <PackageReference Include="MiniExcel.Rust" Version="$(MiniExcelRustPackageVersion)" />
  </ItemGroup>

</Project>